### PR TITLE
Api

### PR DESCRIPTION
**Pull request by Sentient07**
This was something that I was discussing at NIPS and I felt it necessity more than ever while structuring the theano model zoo. There are a plenty of networks that make use of MLPs and of course Logistic Regression. With this addition, one can do an import from theano itself instead of downloading the code from the sample and saving it as a file for an import. I agree on your points that `scikit-theano` does something like this and you do not want a new Keras/Lasagne inside theano itself. If you allow this, we can restrict addition of code to this module only to the networks that are particularly necessary (keeping it here has tangible effects of reducing code copying) and are very widely used(something that is a part of almost all the deep learning models).

### CODE REVIEW

**Comment by nouiz** [comment]
This PR have junk commits in it. maybe this is due to a bad rebase or that the master of my fork is old. But I think you wanted this PR on Theano itself, not my fork.

My personal opinion is that we won't merge that in Theano. I think a better idea would be to make the DLT example layers respect lasagne interface and so people can just reuse the lasagne layers. Or something similar.

If you still think your idea is a good one, make an issue on Theano about that so that the discussion is there, not in my fork. Colosing the PR has having it in my fork is useless.

**Comment by Sentient07** [comment]
Actually I opened here as travis itself is facing problems and i wanted to give you an idea of what I was talking about. Since MLP is something more than a layer, I doubt lasagne would want that.

**Comment by nouiz** [comment]
I don't think it should be in Theano. We could make a repo of models built
on top of Theano, but that would request building or own framework. So why
not continue in a framework models repo and link to it, complete it
instead? This would remove duplicate work.

**Comment by Sentient07** [comment]
Yes, I understand now. It is indeed leading to a lot of duplicates/repetition of code(which i didn't realize till i started to code) if I build that over `theano` and not over frameworks built on top. Probably we can have more examples in DLT but restrict ourselves to having only the examples that aren't variants of existing ones, and are conceptually completely different. For example, we can have `Graph CNNs`, CRFs, etc.. but not Faster-RCNN, SegDeepM etc..(which are extended variants of CNNs). Do you find this good ?

**Comment by nouiz** [comment]
I'm not sure what is the best. I like the idea of making DLT depend
lasagne, but I didn't check how much code change it would request in the
example layers we have to support that format.

I think this should be discussed in the main theano, not my fork.

**Pull request closed without merging**
