### PR TITLE
Nextml

### PR DESCRIPTION
**Pull request by abergeron**
This is a PR with a bunch of small commit that can act as a review of the presentation.

You can either merge it as-is or cherry-pick what you want from this, I don't mind.

Some slides seemed incomplete and I didn't try to complete them as I'm not sure what you want to do with them.

### CODE REVIEW

**Comment by abergeron** [comment]
I would also note that I'm not a big fan of the ALL CAPS to draw attention to certain terms.  I think this should be part of the presentation, not the visual.

**Comment by nouiz** [comment]
Slides for the Next.ML presentation

**Comment by nouiz** [comment]
Are the smaller size stuff still readable?

**Comment by nouiz** [comment]
I agree on all caps, but i think we need something in the slides. Bold
would be better.

**Pull request merged**
